version: 2
updates:
  - package-ecosystem: docker
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: gomod
    schedule:
      interval: weekly
      day: monday
