version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: strict

linters:
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - funlen
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - staticcheck
    - tagalign
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - whitespace
    - wrapcheck

  settings:
    funlen:
      lines: 200
      statements: 50
      ignore-comments: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true
    tagliatelle:
      case:
        rules:
          json: goCamel
    godot:
      #   declarations - for top level declaration comments (default);
      #   toplevel     - for top level comments;
      #   all          - for all comments.
      scope: toplevel
      exclude:
        - '^ \+.*'
        - '^\+.*'
        - "^ ANCHOR.*"
    loggercheck:
      require-string-key: true
    importas:
      no-unaliased: true
      no-extra-aliases: true
      alias:
        # Kubernetes
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/policy/v1
          alias: policyv1
        - pkg: k8s.io/client-go/applyconfigurations/policy/v1
          alias: policyv1ac
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: k8s.io/client-go/applyconfigurations/apps/v1
          alias: appsv1ac
        - pkg: k8s.io/client-go/applyconfigurations/meta/v1
          alias: metav1ac
        - pkg: k8s.io/client-go/applyconfigurations/core/v1
          alias: corev1ac
        - pkg: k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta4
          alias: kubeadmv1beta4
        - pkg: k8s.io/kubernetes/cmd/kubeadm/app/constants
          alias: konstants
        - pkg: k8s.io/kubernetes/cmd/kubeadm/app/cmd/options
          alias: kommandconstants
        - pkg: k8s.io/api/rbac/v1
          alias: rbacv1
        - pkg: k8s.io/client-go/applyconfigurations/rbac/v1
          alias: rbacv1ac
        - pkg: k8s.io/cluster-bootstrap/token/api
          alias: bootstrapapi
        - pkg: k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1
          alias: kubeletv1beta1
        - pkg: k8s.io/kubelet/config/v1beta1
          alias: kubelettypes
        - pkg: k8s.io/kubernetes/cmd/kube-controller-manager/names
          alias: kubenames
        - pkg: k8s.io/client-go/tools/clientcmd/api/v1
          alias: kubeconfigv1
        - pkg: k8s.io/component-base/config/v1alpha1
          alias: componentbaseconfigalpha1
        - pkg: k8s.io/kube-proxy/config/v1alpha1
          alias: kubeproxyv1alpha1
        - pkg: k8s.io/kubernetes/cmd/kubeadm/app/util
          alias: kubeadmutil
        - pkg: k8s.io/api/networking/v1
          alias: networkingv1
        - pkg: k8s.io/client-go/applyconfigurations/networking/v1
          alias: networkingv1ac
        - pkg: k8s.io/client-go/kubernetes/typed/networking/v1
          alias: networkininterface
        - pkg: k8s.io/utils/net
          alias: utilNet
        - pkg: k8s.io/apiserver/pkg/apis/audit/v1
          alias: auditv1

        # Gateway API
        - pkg: sigs.k8s.io/gateway-api/apis/v1
          alias: gwv1
        - pkg: sigs.k8s.io/gateway-api/apis/v1alpha2
          alias: gwv1alpha2
        - pkg: sigs.k8s.io/gateway-api/applyconfiguration/apis/v1
          alias: gwv1ac
        - pkg: sigs.k8s.io/gateway-api/pkg/client/clientset/versioned
          alias: gwclient

        # Controller Runtime
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl

        # CAPI
        - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
          alias: capiv2
        - pkg: sigs.k8s.io/cluster-api/util/secret
          alias: capisecretutil

        # Cert Manager
        - pkg: github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1
          alias: certmanagerv1
        - pkg: github.com/cert-manager/cert-manager/pkg/apis/meta/v1
          alias: certmanagermetav1
        - pkg: github.com/cert-manager/cert-manager/pkg/client/applyconfigurations/certmanager/v1
          alias: certmanagerv1ac
        - pkg: github.com/cert-manager/cert-manager/pkg/client/applyconfigurations/meta/v1
          alias: certmanagermetav1ac
        - pkg: github.com/cert-manager/cert-manager/pkg/client/clientset/versioned
          alias: cmclient

        # Cilium
        - pkg: github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2
          alias: ciliumv2
        - pkg: github.com/cilium/cilium/pkg/k8s/client/clientset/versioned
          alias: ciliumclient
        - pkg: github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1
          alias: ciliummetav1
        - pkg: github.com/cilium/cilium/pkg/k8s/apis/cilium.io
          alias: cilium
        - pkg: github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2
          alias: ciliuminterfacev2

        # Third Party Libraries
        - pkg: github.com/samber/lo
          alias: slices
        - pkg: github.com/blang/semver/v4
          alias: semver
        - pkg: github.com/caarlos0/env/v6
          alias: env
        - pkg: go.etcd.io/etcd/client/v3
          alias: clientv3

        # OpenTelemetry
        - pkg: go.opentelemetry.io/otel/semconv/v1.38.0
          alias: semconv

        # hcp
        - pkg: github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/util/errors
          alias: errorsUtil
        - pkg: github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/operator/util/controller
          alias: controllerUtil
        - pkg: github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/operator/util
          alias: operatorutil
        - pkg: github.com/teutonet/cluster-api-provider-hosted-control-plane/api/v1alpha1/webhook
          alias: webhookv1alpha1

    nolintlint:
      allow-unused: false
      require-specific: true
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: use log package instead
          # stupid go
          # original regex: sigs.k8s.io/cluster-api-provider-openstack/api/(?!v1beta1)
        - pkg: sigs.k8s.io/cluster-api-provider-openstack/api/([^v]|v[^1]|v1[^b]|v1b[^e]|v1be[^t]|v1bet[^a]|v1beta[^1])
          msg: use v1beta1 package instead
        - pkg: github.com/gophercloud/(gophercloud|utils)/([^v]|v[^2])
          msg: use v2 package instead
        #        - pattern: ^controllerutil\.CreateOrPatch$
        #          msg: use SSA instead
        # original regex: slog\.Logger\.(Info|Error|Debug|Warn)(?!Context)
        - pattern: ^slog\.Logger\.(Info|Error|Debug|Warn)(|[^C]|C[^o]|Co[^n]|Con[^t]|Cont[^e]|Conte[^x]|Contex[^t])$
          msg: Use the Context version
        # - pattern: ^controllerruntime.LoggerFrom$
        #   msg: Use 'logr.FromContextAsSlogLogger(ctx)' instead
        # - pattern: ^logr.Logger
        #   msg: Use slog instead
        - pattern: ^(record|events)\.NewFakeRecorder(For)?$
          msg: Use pkg/operator/util/recorder/fake_recorder.go instead.
    revive:
      rules:
        - name: exported
          disabled: true
    gosec:
      excludes:
        - G307 # Deferring unsafe method "Close" on type "\*os.File"
        - G108 # Profiling endpoint is automatically exposed on /debug/pprof
        - G601 # not needed in 1.22, see https://github.com/securego/gosec/issues/1099#issuecomment-1938285468
    gocritic:
      enabled-tags:
        - experimental
      disabled-checks:
        #- dupImport # https://github.com/go-critic/go-critic/issues/845
        - evalOrder
        - octalLiteral
        - unnamedResult
    perfsprint:
      strconcat: false
    wrapcheck:
      ignore-sig-regexps:
        - func github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/util/tracing\.WithSpan[0-9]*
        - func \(\*github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/reconcilers\.(Workload|Management)ResourceReconciler\)\.Reconcile\S+
      extra-ignore-sigs:
        - func github.com/teutonet/cluster-api-provider-hosted-control-plane/pkg/util/errors.IfErrErrorf
  exclusions:
    generated: strict
    rules:
      - linters:
          - lll
        source: "^//\\+kubebuilder.*"
      - linters:
          - lll
        source: ".*https.*" # URLs are long 🤷
      - linters:
          - importas
        text: 'has alias "" which is not' # Why the fuck aren't empty aliases allowed?!
      - linters:
          - importas
        text: 'import ".*/v[0-9]+" imported without alias but must be with alias ".*" according to config' # stupid go...
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      # Disable unparam "always receives" which might not be really
      # useful when building libraries.
      - linters:
          - unparam
        text: always receives
      # Dot imports for gomega or ginkgo are allowed
      # within test files.
      - text: should not use dot imports
        path: &testFiles _test\.go|test/.*\.go
      - text: cyclomatic complexity
        path: *testFiles
      - text: 'shadow:'
        path: *testFiles
      - linters:
          - err113
          - varnamelen
          - funlen
          - nestif
          - importas
          - gosec
          - wrapcheck
        path: *testFiles
      # Append should be able to assign to a different var/slice.
      #- linters:
      #    - gocritic
      #  text: "appendAssign: append result not assigned to the same slice"
      # We don't care about defer in for loops in test files.
      - linters:
          - gocritic
        text: "deferInLoop: Possible resource leak, 'defer' is called in the 'for' loop"
        path: *testFiles

run:
  timeout: 10m
  build-tags:
    - tools
    - e2e
  allow-parallel-runners: true

issues:
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    code-climate:
      path: _artifacts/golangci-lint.json
    text:
      path: stdout
  sort-order:
    - file
    - severity
    - linter
