package v1alpha1

// HostedControlPlane.

const (
	APIServerServiceReadyCondition         = "APIServerServiceReady"
	APIServerServiceFailedReason           = "APIServerServiceFailed"
	APIServerTLSRoutesReadyCondition       = "APIServerTLSRoutesReady"
	APIServerTLSRoutesFailedReason         = "APIServerTLSRoutesFailed"
	SyncControlPlaneEndpointReadyCondition = "SyncControlPlaneEndpointReady"
	SyncControlPlaneEndpointFailedReason   = "SyncControlPlaneEndpointFailed"
	APIServerDeploymentsReadyCondition     = "APIServerDeploymentsReady"
	APIServerDeploymentsFailedReason       = "APIServerDeploymentsFailed"
	CACertificatesReadyCondition           = "CACertificatesReady"
	CACertificatesFailedReason             = "CACertificatesFailed"
	CABundleReadyCondition                 = "CABundleReady"
	CABundleFailedReason                   = "CABundleFailed"
	CARotationAnnotationReadyCondition     = "CARotationAnnotationReady"
	CARotationAnnotationFailedReason       = "CARotationAnnotationFailed"
	CertificatesReadyCondition             = "CertificatesReady"
	CertificatesFailedReason               = "CertificatesFailed"
	InternalKubeconfigReadyCondition       = "InternalKubeconfigReady"
	InternalKubeconfigFailedReason         = "InternalKubeconfigFailed"
	AdminKubeconfigReadyCondition          = "AdminKubeconfigReady"
	AdminKubeconfigFailedReason            = "AdminKubeconfigFailed"
	EtcdClusterReadyCondition              = "EtcdClusterReady"
	EtcdClusterFailedReason                = "EtcdClusterFailed"
	WorkloadClusterResourcesReadyCondition = "WorkloadSetupReady"
	WorkloadClusterResourcesFailedReason   = "WorkloadSetupFailed"
	WorkloadRBACReadyCondition             = "WorkloadRBACReady"
	WorkloadRBACFailedReason               = "WorkloadRBACFailed"
	WorkloadClusterInfoReadyCondition      = "WorkloadClusterInfoReady"
	WorkloadClusterInfoFailedReason        = "WorkloadClusterInfoFailed"
	WorkloadKubeadmConfigReadyCondition    = "WorkloadKubeadmConfigReady"
	WorkloadKubeadmConfigFailedReason      = "WorkloadKubeadmConfigFailed"
	WorkloadKubeletConfigReadyCondition    = "WorkloadKubeletConfigReady"
	WorkloadKubeletConfigFailedReason      = "WorkloadKubeletConfigFailed"
	WorkloadKonnectivityReadyCondition     = "WorkloadKonnectivityReady"
	WorkloadKonnectivityFailedReason       = "WorkloadKonnectivityFailed"
	WorkloadCoreDNSReadyCondition          = "WorkloadCoreDNSReady"
	WorkloadCoreDNSFailedReason            = "WorkloadCoreDNSFailed"
	WorkloadKubeProxyReadyCondition        = "WorkloadKubeProxyReady"
	WorkloadKubeProxyFailedReason          = "WorkloadKubeProxyFailed"
)
