//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerPod) DeepCopyInto(out *APIServerPod) {
	*out = *in
	in.HostedControlPlanePod.DeepCopyInto(&out.HostedControlPlanePod)
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make(map[string]HostedControlPlaneMount, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Konnectivity.DeepCopyInto(&out.Konnectivity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerPod.
func (in *APIServerPod) DeepCopy() *APIServerPod {
	if in == nil {
		return nil
	}
	out := new(APIServerPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDBackup) DeepCopyInto(out *ETCDBackup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDBackup.
func (in *ETCDBackup) DeepCopy() *ETCDBackup {
	if in == nil {
		return nil
	}
	out := new(ETCDBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ETCDComponent) DeepCopyInto(out *ETCDComponent) {
	*out = *in
	out.VolumeSize = in.VolumeSize.DeepCopy()
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(ETCDBackup)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ETCDComponent.
func (in *ETCDComponent) DeepCopy() *ETCDComponent {
	if in == nil {
		return nil
	}
	out := new(ETCDComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlane) DeepCopyInto(out *HostedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlane.
func (in *HostedControlPlane) DeepCopy() *HostedControlPlane {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneContainer) DeepCopyInto(out *HostedControlPlaneContainer) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneContainer.
func (in *HostedControlPlaneContainer) DeepCopy() *HostedControlPlaneContainer {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneDeployment) DeepCopyInto(out *HostedControlPlaneDeployment) {
	*out = *in
	in.APIServer.DeepCopyInto(&out.APIServer)
	in.ControllerManager.DeepCopyInto(&out.ControllerManager)
	in.Scheduler.DeepCopyInto(&out.Scheduler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneDeployment.
func (in *HostedControlPlaneDeployment) DeepCopy() *HostedControlPlaneDeployment {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneInlineSpec) DeepCopyInto(out *HostedControlPlaneInlineSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	out.Gateway = in.Gateway
	in.KonnectivityClient.DeepCopyInto(&out.KonnectivityClient)
	in.KubeProxy.DeepCopyInto(&out.KubeProxy)
	if in.ETCD != nil {
		in, out := &in.ETCD, &out.ETCD
		*out = new(ETCDComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneInlineSpec.
func (in *HostedControlPlaneInlineSpec) DeepCopy() *HostedControlPlaneInlineSpec {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneInlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneList) DeepCopyInto(out *HostedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneList.
func (in *HostedControlPlaneList) DeepCopy() *HostedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneMount) DeepCopyInto(out *HostedControlPlaneMount) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(v1.ConfigMapVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.SecretVolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneMount.
func (in *HostedControlPlaneMount) DeepCopy() *HostedControlPlaneMount {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlanePod) DeepCopyInto(out *HostedControlPlanePod) {
	*out = *in
	in.HostedControlPlaneContainer.DeepCopyInto(&out.HostedControlPlaneContainer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlanePod.
func (in *HostedControlPlanePod) DeepCopy() *HostedControlPlanePod {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlanePod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneSpec) DeepCopyInto(out *HostedControlPlaneSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.HostedControlPlaneInlineSpec.DeepCopyInto(&out.HostedControlPlaneInlineSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneSpec.
func (in *HostedControlPlaneSpec) DeepCopy() *HostedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneStatus) DeepCopyInto(out *HostedControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ETCDVolumeSize = in.ETCDVolumeSize.DeepCopy()
	out.ETCDVolumeUsage = in.ETCDVolumeUsage.DeepCopy()
	in.ETCDLastBackupTime.DeepCopyInto(&out.ETCDLastBackupTime)
	in.ETCDNextBackupTime.DeepCopyInto(&out.ETCDNextBackupTime)
	if in.ExternalManagedControlPlane != nil {
		in, out := &in.ExternalManagedControlPlane, &out.ExternalManagedControlPlane
		*out = new(bool)
		**out = **in
	}
	if in.V1Beta2 != nil {
		in, out := &in.V1Beta2, &out.V1Beta2
		*out = new(HostedControlPlaneV1Beta2Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneStatus.
func (in *HostedControlPlaneStatus) DeepCopy() *HostedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneTemplate) DeepCopyInto(out *HostedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneTemplate.
func (in *HostedControlPlaneTemplate) DeepCopy() *HostedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneTemplateList) DeepCopyInto(out *HostedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneTemplateList.
func (in *HostedControlPlaneTemplateList) DeepCopy() *HostedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneTemplateResource) DeepCopyInto(out *HostedControlPlaneTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneTemplateResource.
func (in *HostedControlPlaneTemplateResource) DeepCopy() *HostedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneTemplateSpec) DeepCopyInto(out *HostedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneTemplateSpec.
func (in *HostedControlPlaneTemplateSpec) DeepCopy() *HostedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedControlPlaneV1Beta2Status) DeepCopyInto(out *HostedControlPlaneV1Beta2Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedControlPlaneV1Beta2Status.
func (in *HostedControlPlaneV1Beta2Status) DeepCopy() *HostedControlPlaneV1Beta2Status {
	if in == nil {
		return nil
	}
	out := new(HostedControlPlaneV1Beta2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeProxyComponent) DeepCopyInto(out *KubeProxyComponent) {
	*out = *in
	in.HostedControlPlanePod.DeepCopyInto(&out.HostedControlPlanePod)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeProxyComponent.
func (in *KubeProxyComponent) DeepCopy() *KubeProxyComponent {
	if in == nil {
		return nil
	}
	out := new(KubeProxyComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalableHostedControlPlanePod) DeepCopyInto(out *ScalableHostedControlPlanePod) {
	*out = *in
	in.HostedControlPlanePod.DeepCopyInto(&out.HostedControlPlanePod)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalableHostedControlPlanePod.
func (in *ScalableHostedControlPlanePod) DeepCopy() *ScalableHostedControlPlanePod {
	if in == nil {
		return nil
	}
	out := new(ScalableHostedControlPlanePod)
	in.DeepCopyInto(out)
	return out
}
