apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-leader-election
  namespace: system
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-leader-election
  namespace: manager-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-leader-election
subjects:
  - kind: ServiceAccount
    name: manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager
subjects:
  - kind: ServiceAccount
    name: manager-controller-manager
