apiVersion: v1
kind: Service
metadata:
  name: controller-manager
spec:
  ports:
    - port: 443
      name: webhooks
      targetPort: webhooks
    - port: 8080
      name: metrics
      targetPort: metrics
