apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: manager-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-service
  namespace: manager-system
spec:
  dnsNames:
    - SERVICE_NAME.SERVICE_NAMESPACE.svc
    - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned
  secretName: capi-hosted-control-plane-webhook-service-certificate # seems like kustomize is too stupid to prefix this...
  subject:
    organizations:
      - k8s-sig-cluster-lifecycle
